-- 12_seed_data.sql
-- Contains Initial Setup, Roles, Permissions, Plans

-- 1. Insert Base Plans
INSERT INTO plans (name, description, price_monthly, price_annual, max_employees, max_admins, max_storage_gb, ai_requests_limit) VALUES
('Trial', '14-day free trial', 0.00, 0.00, 10, 1, 1, 100),
('Starter', 'For small teams', 49.00, 490.00, 50, 3, 10, 1000),
('Professional', 'For growing businesses', 149.00, 1490.00, 200, 10, 50, 5000),
('Enterprise', 'For large organizations', 499.00, 4990.00, 1000, 50, 500, 50000);

-- 2. Insert Permissions
-- Platform/Super Admin
INSERT INTO permissions (name, resource, action, description) VALUES
('platform.manage', 'platform', 'manage', 'Full access to platform operations'),
('organizations.view', 'organizations', 'view', 'View organizations'),
('organizations.manage', 'organizations', 'manage', 'Manage organizations'),
('subscriptions.manage', 'subscriptions', 'manage', 'Manage plans and subscriptions');

-- Employee
INSERT INTO permissions (name, resource, action, description) VALUES
('employee.view', 'employee', 'view', 'View employee data'),
('employee.create', 'employee', 'create', 'Create new employee'),
('employee.update', 'employee', 'update', 'Update employee data'),
('employee.delete', 'employee', 'delete', 'Delete employee');

-- Attendance
INSERT INTO permissions (name, resource, action, description) VALUES
('attendance.view', 'attendance', 'view', 'View attendance records'),
('attendance.manage', 'attendance', 'manage', 'Manage attendance records');

-- Leave
INSERT INTO permissions (name, resource, action, description) VALUES
('leave.apply', 'leave', 'apply', 'Apply for leave'),
('leave.view', 'leave', 'view', 'View leave requests'),
('leave.approve', 'leave', 'approve', 'Approve or reject leave requests');

-- Payroll
INSERT INTO permissions (name, resource, action, description) VALUES
('payroll.view', 'payroll', 'view', 'View payroll data'),
('payroll.create', 'payroll', 'create', 'Create payroll data'),
('payroll.edit', 'payroll', 'edit', 'Edit payroll data'),
('payroll.approve', 'payroll', 'approve', 'Approve payroll processing');

-- Recruitment
INSERT INTO permissions (name, resource, action, description) VALUES
('recruitment.view', 'recruitment', 'view', 'View recruitment data'),
('recruitment.manage', 'recruitment', 'manage', 'Manage recruitment process');

-- Reports
INSERT INTO permissions (name, resource, action, description) VALUES
('reports.view', 'reports', 'view', 'View reports'),
('reports.export', 'reports', 'export', 'Export reports');

-- 3. Create System Roles (Organization = NULL)
INSERT INTO roles (organization_id, name, description, is_system_role) VALUES
(NULL, 'SUPER_ADMIN', 'Platform Administrator', TRUE),
(NULL, 'ORG_ADMIN', 'Organization Administrator', TRUE),
(NULL, 'HR_ADMIN', 'Human Resources Administrator', TRUE),
(NULL, 'PAYROLL_MANAGER', 'Payroll Manager', TRUE),
(NULL, 'MANAGER', 'Department or Team Manager', TRUE),
(NULL, 'FINANCE', 'Finance Role', TRUE),
(NULL, 'EMPLOYEE', 'Standard Employee', TRUE);

-- 4. Map Permissions to SUPER_ADMIN (Gets all platform permissions)
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p
WHERE r.name = 'SUPER_ADMIN' AND p.resource IN ('platform', 'organizations', 'subscriptions');

-- 5. Create a Super Admin User
-- Password is 'password123' 
-- Hash generated by bcrypt.hashSync('password123', 10)
INSERT INTO users (organization_id, email, password_hash, first_name, last_name, status) VALUES
(NULL, 'superadmin@hrms.com', '$2b$10$xOYsgf/2m8/LP4s.ta7itOq.MkzKjIlM5eeczHvgD1K0ZiL9XP7re', 'Super', 'Admin', 'active');

-- Map Super Admin User to SUPER_ADMIN role
INSERT INTO user_roles (user_id, role_id)
SELECT u.id, r.id FROM users u, roles r
WHERE u.email = 'superadmin@hrms.com' AND r.name = 'SUPER_ADMIN';
